### PR TITLE
Include <sched.h> where needed

### PR DESCRIPTION
**Pull request by euspectre**
Many of the reproducers use setns() function but not all of them have `#include <sched.h>` directly or via some other header.

This causes the following warnings during the build in Ubuntu 18.04
and CentOS 8:

>   linux/3272058eb0f2ce2376e9cd97ea997d77f6b487e7.c: In function 'initialize_devlink_pci':
>   linux/3272058eb0f2ce2376e9cd97ea997d77f6b487e7.c:257:13: warning:
>     implicit declaration of function 'setns'; did you mean 'setenv'? [-Wimplicit-function-declaration]
>       int ret = setns(kInitNetNsFd, 0);

Let us add "#include <sched.h>" where it is missing.

### CODE REVIEW

**Comment by dvyukov** [comment]
Does it still happen with newer reproducers (e.g. added in cc69e2b0399ed59b03e65f7c70c19cd126fef9cd)?
If yes, we need to fix syzkaller code that produces them. But we seem to have <sched.h> with initialize_devlink_pci:
https://github.com/google/syzkaller/blob/a0092f9dfdd33924abe5cf5565e4ec4748217c7b/executor/common_linux.h#L709-L711
